server:
  port: 8000
  servlet:
    context-path: /provide
spring:
  application:
    name: service-provide

eureka:
  client:
    #??????????Eureka???true
    register-with-eureka: true
    #???EurekaServer?????????,???true???????,???????true????Ribbon??????
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka


